// POS and Management System Data - Enhanced Version

export interface Product {
  id: string
  name: string
  category: string
  price: number
  cost: number
  stock: number
  minStock: number
  image: string
  description: string
  isAvailable: boolean
  preparationTime: number
  calories?: number
  ingredients: string[]
  createdAt: Date
  updatedAt: Date
  soldToday: number
  soldThisMonth: number
}

export interface Category {
  id: string
  name: string
  icon: string
  color: string
  isActive: boolean
  productCount: number
  description: string
}

export interface Order {
  id: string
  orderNumber: string
  items: OrderItem[]
  subtotal: number
  tax: number
  discount: number
  total: number
  paymentMethod: string
  status: "pending" | "preparing" | "ready" | "completed" | "cancelled"
  customerName?: string
  customerPhone?: string
  orderType: "dine-in" | "takeaway" | "delivery"
  tableNumber?: number
  timestamp: Date
  completedAt?: Date
  notes?: string
  cashierName: string
  preparationTime?: number
}

export interface OrderItem {
  productId: string
  name: string
  price: number
  quantity: number
  notes?: string
  modifiers?: Modifier[]
}

export interface Modifier {
  id: string
  name: string
  price: number
}

export interface Staff {
  id: string
  name: string
  role: "cashier" | "manager" | "chef" | "waiter" | "admin"
  email: string
  phone: string
  shift: string
  isActive: boolean
  permissions: string[]
  avatar: string
  joinDate: string
  salary: number
  address: string
  emergencyContact: string
  performance: {
    ordersHandled: number
    customerRating: number
    punctuality: number
    efficiency: number
  }
  schedule: {
    monday: string
    tuesday: string
    wednesday: string
    thursday: string
    friday: string
    saturday: string
    sunday: string
  }
}

export interface Customer {
  id: string
  name: string
  phone: string
  email?: string
  address?: string
  totalOrders: number
  totalSpent: number
  lastVisit: Date
  loyaltyPoints: number
  memberSince: string
  favoriteItems: string[]
  averageOrderValue: number
  visitFrequency: number
}

export interface Table {
  id: string
  number: number
  capacity: number
  status: "available" | "occupied" | "reserved" | "cleaning"
  currentOrder?: string
  location: string
  reservedBy?: string
  reservedAt?: Date
}

export interface InventoryItem {
  id: string
  name: string
  category: "ingredients" | "packaging" | "supplies" | "equipment"
  currentStock: number
  minStock: number
  maxStock: number
  unit: string
  costPerUnit: number
  supplier: string
  lastRestocked: Date
  expiryDate?: Date
  location: string
  status: "in-stock" | "low-stock" | "out-of-stock" | "expired"
}

export interface Supplier {
  id: string
  name: string
  contact: string
  email: string
  address: string
  products: string[]
  rating: number
  paymentTerms: string
  deliveryDays: string[]
}

export interface SalesAnalytics {
  date: string
  revenue: number
  orders: number
  customers: number
  averageOrderValue: number
  topSellingItems: { name: string; quantity: number; revenue: number }[]
  hourlyBreakdown: { hour: number; revenue: number; orders: number }[]
}

// Enhanced Categories
export const categories: Category[] = [
  {
    id: "1",
    name: "Kopi",
    icon: "Coffee",
    color: "#8B4513",
    isActive: true,
    productCount: 8,
    description: "Berbagai jenis kopi premium dari biji pilihan",
  },
  {
    id: "2",
    name: "Makanan",
    icon: "UtensilsCrossed",
    color: "#FF6B35",
    isActive: true,
    productCount: 12,
    description: "Makanan berat dan ringan untuk segala waktu",
  },
  {
    id: "3",
    name: "Minuman Dingin",
    icon: "GlassWater",
    color: "#4A90E2",
    isActive: true,
    productCount: 10,
    description: "Minuman segar dan menyegarkan",
  },
  {
    id: "4",
    name: "Snack",
    icon: "Cookie",
    color: "#F39C12",
    isActive: true,
    productCount: 8,
    description: "Camilan dan makanan ringan",
  },
  {
    id: "5",
    name: "Dessert",
    icon: "IceCream",
    color: "#E91E63",
    isActive: true,
    productCount: 6,
    description: "Penutup manis untuk melengkapi hidangan",
  },
]

// Enhanced Products (44 items)
export const products: Product[] = [
  // Kopi (8 items)
  {
    id: "1",
    name: "Kopi Susu Gula Aren",
    category: "Kopi",
    price: 18000,
    cost: 7000,
    stock: 50,
    minStock: 10,
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&h=300&fit=crop",
    description: "Kopi arabika premium dengan susu segar dan gula aren asli",
    isAvailable: true,
    preparationTime: 5,
    calories: 180,
    ingredients: ["Kopi Arabika", "Susu Segar", "Gula Aren", "Es Batu"],
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 25,
    soldThisMonth: 450,
  },
  {
    id: "2",
    name: "Es Kopi Susu",
    category: "Kopi",
    price: 15000,
    cost: 6000,
    stock: 45,
    minStock: 10,
    image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&h=300&fit=crop",
    description: "Kopi dingin dengan susu creamy yang menyegarkan",
    isAvailable: true,
    preparationTime: 3,
    calories: 150,
    ingredients: ["Kopi", "Susu", "Gula", "Es Batu"],
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 18,
    soldThisMonth: 380,
  },
  {
    id: "3",
    name: "Americano",
    category: "Kopi",
    price: 12000,
    cost: 4000,
    stock: 60,
    minStock: 15,
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400&h=300&fit=crop",
    description: "Espresso shot dengan air panas, rasa kopi murni",
    isAvailable: true,
    preparationTime: 3,
    calories: 5,
    ingredients: ["Espresso", "Air Panas"],
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 12,
    soldThisMonth: 220,
  },
  {
    id: "4",
    name: "Cappuccino",
    category: "Kopi",
    price: 16000,
    cost: 6500,
    stock: 40,
    minStock: 10,
    image: "https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=400&h=300&fit=crop",
    description: "Espresso dengan steamed milk dan foam yang creamy",
    isAvailable: true,
    preparationTime: 4,
    calories: 120,
    ingredients: ["Espresso", "Susu", "Foam"],
    createdAt: new Date("2023-02-01"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 15,
    soldThisMonth: 280,
  },
  {
    id: "5",
    name: "Latte",
    category: "Kopi",
    price: 17000,
    cost: 7000,
    stock: 35,
    minStock: 10,
    image: "https://images.unsplash.com/photo-1561882468-9110e03e0f78?w=400&h=300&fit=crop",
    description: "Espresso dengan steamed milk dan sedikit foam",
    isAvailable: true,
    preparationTime: 4,
    calories: 140,
    ingredients: ["Espresso", "Steamed Milk", "Foam"],
    createdAt: new Date("2023-02-01"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 20,
    soldThisMonth: 350,
  },
  {
    id: "6",
    name: "Mocha",
    category: "Kopi",
    price: 19000,
    cost: 8000,
    stock: 30,
    minStock: 8,
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop",
    description: "Perpaduan espresso, cokelat, dan steamed milk",
    isAvailable: true,
    preparationTime: 5,
    calories: 200,
    ingredients: ["Espresso", "Cokelat", "Steamed Milk", "Whipped Cream"],
    createdAt: new Date("2023-03-01"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 8,
    soldThisMonth: 180,
  },
  {
    id: "7",
    name: "Espresso",
    category: "Kopi",
    price: 10000,
    cost: 3500,
    stock: 80,
    minStock: 20,
    image: "https://images.unsplash.com/photo-1510707577719-ae7c14805e3a?w=400&h=300&fit=crop",
    description: "Shot espresso murni untuk pecinta kopi sejati",
    isAvailable: true,
    preparationTime: 2,
    calories: 3,
    ingredients: ["Espresso"],
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 5,
    soldThisMonth: 95,
  },
  {
    id: "8",
    name: "Kopi Tubruk",
    category: "Kopi",
    price: 8000,
    cost: 3000,
    stock: 70,
    minStock: 15,
    image: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=400&h=300&fit=crop",
    description: "Kopi tradisional Indonesia dengan gula pasir",
    isAvailable: true,
    preparationTime: 3,
    calories: 80,
    ingredients: ["Kopi Bubuk", "Gula Pasir", "Air Panas"],
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 10,
    soldThisMonth: 150,
  },

  // Makanan (12 items)
  {
    id: "9",
    name: "Nasi Goreng Spesial",
    category: "Makanan",
    price: 25000,
    cost: 12000,
    stock: 30,
    minStock: 5,
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400&h=300&fit=crop",
    description: "Nasi goreng dengan telur, ayam, dan sayuran segar",
    isAvailable: true,
    preparationTime: 15,
    calories: 450,
    ingredients: ["Nasi", "Telur", "Ayam", "Sayuran", "Bumbu Spesial"],
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 22,
    soldThisMonth: 320,
  },
  {
    id: "10",
    name: "Ayam Geprek",
    category: "Makanan",
    price: 22000,
    cost: 10000,
    stock: 25,
    minStock: 5,
    image: "https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400&h=300&fit=crop",
    description: "Ayam crispy dengan sambal geprek pedas dan nasi",
    isAvailable: true,
    preparationTime: 12,
    calories: 520,
    ingredients: ["Ayam", "Tepung", "Sambal", "Nasi", "Lalapan"],
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 18,
    soldThisMonth: 280,
  },
  {
    id: "11",
    name: "Mie Ayam",
    category: "Makanan",
    price: 20000,
    cost: 9000,
    stock: 35,
    minStock: 8,
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&h=300&fit=crop",
    description: "Mie dengan topping ayam, pangsit, dan sayuran",
    isAvailable: true,
    preparationTime: 10,
    calories: 380,
    ingredients: ["Mie", "Ayam", "Pangsit", "Sayuran", "Kuah"],
    createdAt: new Date("2023-02-01"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 15,
    soldThisMonth: 240,
  },
  {
    id: "12",
    name: "Gado-Gado",
    category: "Makanan",
    price: 18000,
    cost: 8000,
    stock: 20,
    minStock: 5,
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop",
    description: "Salad Indonesia dengan bumbu kacang yang khas",
    isAvailable: true,
    preparationTime: 8,
    calories: 320,
    ingredients: ["Sayuran", "Tahu", "Tempe", "Telur", "Bumbu Kacang"],
    createdAt: new Date("2023-02-15"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 8,
    soldThisMonth: 120,
  },
  {
    id: "13",
    name: "Soto Ayam",
    category: "Makanan",
    price: 23000,
    cost: 11000,
    stock: 28,
    minStock: 6,
    image: "https://images.unsplash.com/photo-1569059078571-45d8c6b8b9b8?w=400&h=300&fit=crop",
    description: "Sup ayam tradisional dengan kuah kuning yang hangat",
    isAvailable: true,
    preparationTime: 12,
    calories: 350,
    ingredients: ["Ayam", "Kuah Soto", "Nasi", "Telur", "Kerupuk"],
    createdAt: new Date("2023-03-01"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 12,
    soldThisMonth: 180,
  },
  {
    id: "14",
    name: "Sandwich Club",
    category: "Makanan",
    price: 24000,
    cost: 11500,
    stock: 22,
    minStock: 5,
    image: "https://images.unsplash.com/photo-1539252554453-80ab65ce3586?w=400&h=300&fit=crop",
    description: "Sandwich berlapis dengan ayam, bacon, dan sayuran",
    isAvailable: true,
    preparationTime: 8,
    calories: 480,
    ingredients: ["Roti", "Ayam", "Bacon", "Selada", "Tomat", "Mayo"],
    createdAt: new Date("2023-03-15"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 6,
    soldThisMonth: 95,
  },
  {
    id: "15",
    name: "Burger Beef",
    category: "Makanan",
    price: 28000,
    cost: 14000,
    stock: 18,
    minStock: 4,
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop",
    description: "Burger daging sapi dengan keju dan sayuran segar",
    isAvailable: true,
    preparationTime: 15,
    calories: 580,
    ingredients: ["Roti Burger", "Daging Sapi", "Keju", "Selada", "Tomat"],
    createdAt: new Date("2023-04-01"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 9,
    soldThisMonth: 140,
  },
  {
    id: "16",
    name: "Pasta Carbonara",
    category: "Makanan",
    price: 26000,
    cost: 12500,
    stock: 20,
    minStock: 4,
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc353d2e5?w=400&h=300&fit=crop",
    description: "Pasta dengan saus krim, bacon, dan keju parmesan",
    isAvailable: true,
    preparationTime: 12,
    calories: 520,
    ingredients: ["Pasta", "Krim", "Bacon", "Keju Parmesan", "Telur"],
    createdAt: new Date("2023-04-15"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 7,
    soldThisMonth: 110,
  },
  {
    id: "17",
    name: "Nasi Uduk",
    category: "Makanan",
    price: 19000,
    cost: 8500,
    stock: 25,
    minStock: 6,
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=300&fit=crop",
    description: "Nasi gurih dengan lauk pauk lengkap",
    isAvailable: true,
    preparationTime: 10,
    calories: 420,
    ingredients: ["Nasi Uduk", "Ayam", "Tempe", "Tahu", "Sambal"],
    createdAt: new Date("2023-05-01"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 11,
    soldThisMonth: 165,
  },
  {
    id: "18",
    name: "Rendang",
    category: "Makanan",
    price: 32000,
    cost: 16000,
    stock: 15,
    minStock: 3,
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400&h=300&fit=crop",
    description: "Daging sapi rendang dengan bumbu rempah tradisional",
    isAvailable: true,
    preparationTime: 20,
    calories: 480,
    ingredients: ["Daging Sapi", "Santan", "Bumbu Rendang", "Nasi"],
    createdAt: new Date("2023-05-15"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 5,
    soldThisMonth: 85,
  },
  {
    id: "19",
    name: "Fried Rice Seafood",
    category: "Makanan",
    price: 29000,
    cost: 14500,
    stock: 20,
    minStock: 4,
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400&h=300&fit=crop",
    description: "Nasi goreng dengan seafood segar dan bumbu spesial",
    isAvailable: true,
    preparationTime: 18,
    calories: 510,
    ingredients: ["Nasi", "Udang", "Cumi", "Telur", "Sayuran"],
    createdAt: new Date("2023-06-01"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 8,
    soldThisMonth: 120,
  },
  {
    id: "20",
    name: "Chicken Wings",
    category: "Makanan",
    price: 21000,
    cost: 9500,
    stock: 30,
    minStock: 6,
    image: "https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=400&h=300&fit=crop",
    description: "Sayap ayam crispy dengan saus BBQ atau pedas",
    isAvailable: true,
    preparationTime: 15,
    calories: 380,
    ingredients: ["Sayap Ayam", "Tepung", "Saus BBQ", "Bumbu"],
    createdAt: new Date("2023-06-15"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 14,
    soldThisMonth: 210,
  },

  // Minuman Dingin (10 items)
  {
    id: "21",
    name: "Es Teh Manis",
    category: "Minuman Dingin",
    price: 8000,
    cost: 2000,
    stock: 80,
    minStock: 20,
    image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=300&fit=crop",
    description: "Teh manis dingin yang menyegarkan",
    isAvailable: true,
    preparationTime: 2,
    calories: 120,
    ingredients: ["Teh", "Gula", "Es Batu"],
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 35,
    soldThisMonth: 520,
  },
  {
    id: "22",
    name: "Jus Jeruk",
    category: "Minuman Dingin",
    price: 12000,
    cost: 5000,
    stock: 35,
    minStock: 10,
    image: "https://images.unsplash.com/photo-1613478223719-2ab802602423?w=400&h=300&fit=crop",
    description: "Jus jeruk segar tanpa pengawet",
    isAvailable: true,
    preparationTime: 3,
    calories: 110,
    ingredients: ["Jeruk Segar", "Gula", "Es Batu"],
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 18,
    soldThisMonth: 270,
  },
  {
    id: "23",
    name: "Es Campur",
    category: "Minuman Dingin",
    price: 15000,
    cost: 6000,
    stock: 25,
    minStock: 8,
    image: "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=400&h=300&fit=crop",
    description: "Minuman es dengan berbagai topping tradisional",
    isAvailable: true,
    preparationTime: 5,
    calories: 180,
    ingredients: ["Es Serut", "Sirup", "Agar-agar", "Kelapa", "Kacang"],
    createdAt: new Date("2023-02-01"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 12,
    soldThisMonth: 180,
  },
  {
    id: "24",
    name: "Smoothie Mangga",
    category: "Minuman Dingin",
    price: 16000,
    cost: 7000,
    stock: 20,
    minStock: 6,
    image: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=400&h=300&fit=crop",
    description: "Smoothie mangga segar dengan yogurt",
    isAvailable: true,
    preparationTime: 4,
    calories: 160,
    ingredients: ["Mangga", "Yogurt", "Susu", "Es Batu"],
    createdAt: new Date("2023-02-15"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 9,
    soldThisMonth: 135,
  },
  {
    id: "25",
    name: "Es Kelapa Muda",
    category: "Minuman Dingin",
    price: 13000,
    cost: 5500,
    stock: 30,
    minStock: 8,
    image: "https://images.unsplash.com/photo-1559181567-c3190ca9959b?w=400&h=300&fit=crop",
    description: "Air kelapa muda segar dengan daging kelapa",
    isAvailable: true,
    preparationTime: 3,
    calories: 90,
    ingredients: ["Kelapa Muda", "Es Batu", "Gula"],
    createdAt: new Date("2023-03-01"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 15,
    soldThisMonth: 225,
  },
  {
    id: "26",
    name: "Lemon Tea",
    category: "Minuman Dingin",
    price: 10000,
    cost: 3500,
    stock: 40,
    minStock: 12,
    image: "https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=400&h=300&fit=crop",
    description: "Teh dengan perasan lemon segar",
    isAvailable: true,
    preparationTime: 3,
    calories: 80,
    ingredients: ["Teh", "Lemon", "Gula", "Es Batu"],
    createdAt: new Date("2023-03-15"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 22,
    soldThisMonth: 330,
  },
  {
    id: "27",
    name: "Jus Alpukat",
    category: "Minuman Dingin",
    price: 14000,
    cost: 6500,
    stock: 18,
    minStock: 5,
    image: "https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=400&h=300&fit=crop",
    description: "Jus alpukat creamy dengan susu kental manis",
    isAvailable: true,
    preparationTime: 4,
    calories: 220,
    ingredients: ["Alpukat", "Susu", "Gula", "Es Batu"],
    createdAt: new Date("2023-04-01"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 7,
    soldThisMonth: 105,
  },
  {
    id: "28",
    name: "Es Cincau",
    category: "Minuman Dingin",
    price: 9000,
    cost: 3000,
    stock: 45,
    minStock: 12,
    image: "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=400&h=300&fit=crop",
    description: "Minuman cincau hitam dengan sirup gula merah",
    isAvailable: true,
    preparationTime: 3,
    calories: 100,
    ingredients: ["Cincau", "Sirup", "Santan", "Es Batu"],
    createdAt: new Date("2023-04-15"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 16,
    soldThisMonth: 240,
  },
  {
    id: "29",
    name: "Milkshake Vanilla",
    category: "Minuman Dingin",
    price: 18000,
    cost: 8000,
    stock: 22,
    minStock: 6,
    image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=400&h=300&fit=crop",
    description: "Milkshake vanilla dengan whipped cream",
    isAvailable: true,
    preparationTime: 5,
    calories: 280,
    ingredients: ["Es Krim Vanilla", "Susu", "Whipped Cream"],
    createdAt: new Date("2023-05-01"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 5,
    soldThisMonth: 75,
  },
  {
    id: "30",
    name: "Es Buah",
    category: "Minuman Dingin",
    price: 17000,
    cost: 7500,
    stock: 15,
    minStock: 4,
    image: "https://images.unsplash.com/photo-1546173159-315724a31696?w=400&h=300&fit=crop",
    description: "Campuran buah segar dengan es serut dan sirup",
    isAvailable: true,
    preparationTime: 6,
    calories: 150,
    ingredients: ["Buah Campur", "Es Serut", "Sirup", "Susu Kental"],
    createdAt: new Date("2023-05-15"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 8,
    soldThisMonth: 120,
  },

  // Snack (8 items)
  {
    id: "31",
    name: "Pisang Goreng",
    category: "Snack",
    price: 10000,
    cost: 3000,
    stock: 40,
    minStock: 10,
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&h=300&fit=crop",
    description: "Pisang goreng crispy dengan taburan gula",
    isAvailable: true,
    preparationTime: 8,
    calories: 200,
    ingredients: ["Pisang", "Tepung", "Gula", "Minyak"],
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 28,
    soldThisMonth: 420,
  },
  {
    id: "32",
    name: "Roti Bakar",
    category: "Snack",
    price: 12000,
    cost: 4000,
    stock: 30,
    minStock: 8,
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop",
    description: "Roti bakar dengan selai dan mentega",
    isAvailable: true,
    preparationTime: 5,
    calories: 180,
    ingredients: ["Roti", "Mentega", "Selai", "Keju"],
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 20,
    soldThisMonth: 300,
  },
  {
    id: "33",
    name: "French Fries",
    category: "Snack",
    price: 15000,
    cost: 6000,
    stock: 35,
    minStock: 10,
    image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400&h=300&fit=crop",
    description: "Kentang goreng crispy dengan saus samping",
    isAvailable: true,
    preparationTime: 10,
    calories: 320,
    ingredients: ["Kentang", "Minyak", "Garam", "Saus"],
    createdAt: new Date("2023-02-01"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 25,
    soldThisMonth: 375,
  },
  {
    id: "34",
    name: "Onion Rings",
    category: "Snack",
    price: 13000,
    cost: 5000,
    stock: 25,
    minStock: 6,
    image: "https://images.unsplash.com/photo-1639024471283-03518883512d?w=400&h=300&fit=crop",
    description: "Bawang bombay goreng dengan tepung crispy",
    isAvailable: true,
    preparationTime: 8,
    calories: 250,
    ingredients: ["Bawang Bombay", "Tepung", "Minyak", "Bumbu"],
    createdAt: new Date("2023-02-15"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 12,
    soldThisMonth: 180,
  },
  {
    id: "35",
    name: "Keripik Singkong",
    category: "Snack",
    price: 8000,
    cost: 2500,
    stock: 50,
    minStock: 15,
    image: "https://images.unsplash.com/photo-1621939514649-280e2ee25f60?w=400&h=300&fit=crop",
    description: "Keripik singkong renyah dengan berbagai rasa",
    isAvailable: true,
    preparationTime: 2,
    calories: 150,
    ingredients: ["Singkong", "Minyak", "Garam", "Bumbu"],
    createdAt: new Date("2023-03-01"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 18,
    soldThisMonth: 270,
  },
  {
    id: "36",
    name: "Tahu Crispy",
    category: "Snack",
    price: 11000,
    cost: 4000,
    stock: 28,
    minStock: 8,
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400&h=300&fit=crop",
    description: "Tahu goreng crispy dengan saus kacang",
    isAvailable: true,
    preparationTime: 6,
    calories: 180,
    ingredients: ["Tahu", "Tepung", "Saus Kacang", "Minyak"],
    createdAt: new Date("2023-03-15"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 15,
    soldThisMonth: 225,
  },
  {
    id: "37",
    name: "Bakwan Jagung",
    category: "Snack",
    price: 9000,
    cost: 3500,
    stock: 32,
    minStock: 8,
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&h=300&fit=crop",
    description: "Bakwan jagung manis yang gurih dan renyah",
    isAvailable: true,
    preparationTime: 7,
    calories: 160,
    ingredients: ["Jagung", "Tepung", "Telur", "Bumbu"],
    createdAt: new Date("2023-04-01"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 22,
    soldThisMonth: 330,
  },
  {
    id: "38",
    name: "Nachos",
    category: "Snack",
    price: 16000,
    cost: 7000,
    stock: 20,
    minStock: 5,
    image: "https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?w=400&h=300&fit=crop",
    description: "Keripik jagung dengan keju leleh dan salsa",
    isAvailable: true,
    preparationTime: 5,
    calories: 280,
    ingredients: ["Keripik Jagung", "Keju", "Salsa", "Jalapeno"],
    createdAt: new Date("2023-04-15"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 8,
    soldThisMonth: 120,
  },

  // Dessert (6 items)
  {
    id: "39",
    name: "Es Krim Vanilla",
    category: "Dessert",
    price: 15000,
    cost: 6000,
    stock: 20,
    minStock: 5,
    image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400&h=300&fit=crop",
    description: "Es krim vanilla premium dengan topping",
    isAvailable: true,
    preparationTime: 2,
    calories: 250,
    ingredients: ["Es Krim Vanilla", "Topping", "Wafer"],
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 12,
    soldThisMonth: 180,
  },
  {
    id: "40",
    name: "Brownies",
    category: "Dessert",
    price: 18000,
    cost: 8000,
    stock: 15,
    minStock: 4,
    image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=400&h=300&fit=crop",
    description: "Brownies cokelat hangat dengan es krim",
    isAvailable: true,
    preparationTime: 8,
    calories: 320,
    ingredients: ["Cokelat", "Tepung", "Telur", "Mentega", "Es Krim"],
    createdAt: new Date("2023-02-01"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 8,
    soldThisMonth: 120,
  },
  {
    id: "41",
    name: "Pudding Cokelat",
    category: "Dessert",
    price: 12000,
    cost: 5000,
    stock: 25,
    minStock: 6,
    image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&h=300&fit=crop",
    description: "Pudding cokelat lembut dengan saus karamel",
    isAvailable: true,
    preparationTime: 3,
    calories: 180,
    ingredients: ["Susu", "Cokelat", "Gelatin", "Saus Karamel"],
    createdAt: new Date("2023-02-15"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 10,
    soldThisMonth: 150,
  },
  {
    id: "42",
    name: "Tiramisu",
    category: "Dessert",
    price: 22000,
    cost: 10000,
    stock: 12,
    minStock: 3,
    image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&h=300&fit=crop",
    description: "Tiramisu klasik dengan kopi dan mascarpone",
    isAvailable: true,
    preparationTime: 5,
    calories: 380,
    ingredients: ["Ladyfinger", "Kopi", "Mascarpone", "Cokelat"],
    createdAt: new Date("2023-03-01"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 4,
    soldThisMonth: 60,
  },
  {
    id: "43",
    name: "Cheesecake",
    category: "Dessert",
    price: 20000,
    cost: 9000,
    stock: 18,
    minStock: 4,
    image: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=400&h=300&fit=crop",
    description: "Cheesecake New York dengan berry sauce",
    isAvailable: true,
    preparationTime: 4,
    calories: 350,
    ingredients: ["Cream Cheese", "Graham Cracker", "Berry", "Gula"],
    createdAt: new Date("2023-03-15"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 6,
    soldThisMonth: 90,
  },
  {
    id: "44",
    name: "Panna Cotta",
    category: "Dessert",
    price: 16000,
    cost: 7000,
    stock: 14,
    minStock: 3,
    image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&h=300&fit=crop",
    description: "Panna cotta vanilla dengan coulis buah",
    isAvailable: true,
    preparationTime: 3,
    calories: 220,
    ingredients: ["Krim", "Gelatin", "Vanilla", "Coulis Buah"],
    createdAt: new Date("2023-04-01"),
    updatedAt: new Date("2024-01-20"),
    soldToday: 5,
    soldThisMonth: 75,
  },
]

// Enhanced Staff data
export const staffData: Staff[] = [
  {
    id: "1",
    name: "Sari Dewi",
    role: "manager",
    email: "sari@inaracafe.com",
    phone: "081234567890",
    shift: "Full Time",
    isActive: true,
    permissions: ["all"],
    avatar: "/placeholder.svg?height=100&width=100&text=SD",
    joinDate: "2023-01-15",
    salary: 8000000,
    address: "Jl. Merdeka No. 123, Jakarta",
    emergencyContact: "081234567899 (Suami)",
    performance: {
      ordersHandled: 1250,
      customerRating: 4.9,
      punctuality: 98,
      efficiency: 95,
    },
    schedule: {
      monday: "08:00-17:00",
      tuesday: "08:00-17:00",
      wednesday: "08:00-17:00",
      thursday: "08:00-17:00",
      friday: "08:00-17:00",
      saturday: "08:00-14:00",
      sunday: "Off",
    },
  },
  {
    id: "2",
    name: "Budi Santoso",
    role: "cashier",
    email: "budi@inaracafe.com",
    phone: "081234567891",
    shift: "Pagi",
    isActive: true,
    permissions: ["pos", "orders"],
    avatar: "/placeholder.svg?height=100&width=100&text=BS",
    joinDate: "2023-03-20",
    salary: 4500000,
    address: "Jl. Sudirman No. 456, Jakarta",
    emergencyContact: "081234567898 (Ibu)",
    performance: {
      ordersHandled: 2180,
      customerRating: 4.7,
      punctuality: 95,
      efficiency: 92,
    },
    schedule: {
      monday: "06:00-14:00",
      tuesday: "06:00-14:00",
      wednesday: "06:00-14:00",
      thursday: "06:00-14:00",
      friday: "06:00-14:00",
      saturday: "06:00-14:00",
      sunday: "Off",
    },
  },
  {
    id: "3",
    name: "Maya Putri",
    role: "chef",
    email: "maya@inaracafe.com",
    phone: "081234567892",
    shift: "Siang",
    isActive: true,
    permissions: ["kitchen", "inventory"],
    avatar: "/placeholder.svg?height=100&width=100&text=MP",
    joinDate: "2023-02-10",
    salary: 5500000,
    address: "Jl. Thamrin No. 789, Jakarta",
    emergencyContact: "081234567897 (Ayah)",
    performance: {
      ordersHandled: 1850,
      customerRating: 4.8,
      punctuality: 97,
      efficiency: 94,
    },
    schedule: {
      monday: "10:00-18:00",
      tuesday: "10:00-18:00",
      wednesday: "10:00-18:00",
      thursday: "10:00-18:00",
      friday: "10:00-18:00",
      saturday: "10:00-18:00",
      sunday: "Off",
    },
  },
  {
    id: "4",
    name: "Andi Wijaya",
    role: "waiter",
    email: "andi@inaracafe.com",
    phone: "081234567893",
    shift: "Sore",
    isActive: true,
    permissions: ["orders", "tables"],
    avatar: "/placeholder.svg?height=100&width=100&text=AW",
    joinDate: "2023-04-05",
    salary: 4000000,
    address: "Jl. Gatot Subroto No. 321, Jakarta",
    emergencyContact: "081234567896 (Istri)",
    performance: {
      ordersHandled: 1650,
      customerRating: 4.6,
      punctuality: 90,
      efficiency: 88,
    },
    schedule: {
      monday: "14:00-22:00",
      tuesday: "14:00-22:00",
      wednesday: "14:00-22:00",
      thursday: "14:00-22:00",
      friday: "14:00-22:00",
      saturday: "14:00-22:00",
      sunday: "Off",
    },
  },
  {
    id: "5",
    name: "Rina Sari",
    role: "cashier",
    email: "rina@inaracafe.com",
    phone: "081234567894",
    shift: "Weekend",
    isActive: true,
    permissions: ["pos", "orders"],
    avatar: "/placeholder.svg?height=100&width=100&text=RS",
    joinDate: "2023-05-12",
    salary: 4200000,
    address: "Jl. Kuningan No. 654, Jakarta",
    emergencyContact: "081234567895 (Kakak)",
    performance: {
      ordersHandled: 980,
      customerRating: 4.5,
      punctuality: 93,
      efficiency: 89,
    },
    schedule: {
      monday: "Off",
      tuesday: "Off",
      wednesday: "Off",
      thursday: "Off",
      friday: "Off",
      saturday: "08:00-20:00",
      sunday: "08:00-20:00",
    },
  },
  {
    id: "6",
    name: "Dedi Kurniawan",
    role: "chef",
    email: "dedi@inaracafe.com",
    phone: "081234567895",
    shift: "Malam",
    isActive: true,
    permissions: ["kitchen", "inventory"],
    avatar: "/placeholder.svg?height=100&width=100&text=DK",
    joinDate: "2023-06-18",
    salary: 5200000,
    address: "Jl. Senayan No. 987, Jakarta",
    emergencyContact: "081234567894 (Ibu)",
    performance: {
      ordersHandled: 1420,
      customerRating: 4.7,
      punctuality: 96,
      efficiency: 91,
    },
    schedule: {
      monday: "18:00-02:00",
      tuesday: "18:00-02:00",
      wednesday: "18:00-02:00",
      thursday: "18:00-02:00",
      friday: "18:00-02:00",
      saturday: "18:00-02:00",
      sunday: "Off",
    },
  },
]

// Enhanced Inventory
export const inventoryData: InventoryItem[] = [
  {
    id: "1",
    name: "Biji Kopi Arabika",
    category: "ingredients",
    currentStock: 25,
    minStock: 10,
    maxStock: 50,
    unit: "kg",
    costPerUnit: 150000,
    supplier: "Kopi Nusantara",
    lastRestocked: new Date("2024-01-15"),
    location: "Gudang A-1",
    status: "in-stock",
  },
  {
    id: "2",
    name: "Susu Segar",
    category: "ingredients",
    currentStock: 8,
    minStock: 15,
    maxStock: 30,
    unit: "liter",
    costPerUnit: 15000,
    supplier: "Dairy Fresh",
    lastRestocked: new Date("2024-01-20"),
    expiryDate: new Date("2024-01-25"),
    location: "Kulkas B-2",
    status: "low-stock",
  },
  {
    id: "3",
    name: "Gula Aren",
    category: "ingredients",
    currentStock: 12,
    minStock: 8,
    maxStock: 25,
    unit: "kg",
    costPerUnit: 35000,
    supplier: "Gula Tradisional",
    lastRestocked: new Date("2024-01-18"),
    location: "Gudang A-2",
    status: "in-stock",
  },
  {
    id: "4",
    name: "Beras Premium",
    category: "ingredients",
    currentStock: 45,
    minStock: 20,
    maxStock: 100,
    unit: "kg",
    costPerUnit: 18000,
    supplier: "Beras Berkah",
    lastRestocked: new Date("2024-01-10"),
    location: "Gudang A-3",
    status: "in-stock",
  },
  {
    id: "5",
    name: "Ayam Segar",
    category: "ingredients",
    currentStock: 5,
    minStock: 10,
    maxStock: 20,
    unit: "kg",
    costPerUnit: 35000,
    supplier: "Fresh Chicken",
    lastRestocked: new Date("2024-01-22"),
    expiryDate: new Date("2024-01-24"),
    location: "Kulkas B-1",
    status: "low-stock",
  },
  {
    id: "6",
    name: "Cup Kertas 12oz",
    category: "packaging",
    currentStock: 500,
    minStock: 200,
    maxStock: 1000,
    unit: "pcs",
    costPerUnit: 350,
    supplier: "Packaging Pro",
    lastRestocked: new Date("2024-01-12"),
    location: "Gudang C-1",
    status: "in-stock",
  },
  {
    id: "7",
    name: "Tutup Cup",
    category: "packaging",
    currentStock: 150,
    minStock: 200,
    maxStock: 800,
    unit: "pcs",
    costPerUnit: 250,
    supplier: "Packaging Pro",
    lastRestocked: new Date("2024-01-12"),
    location: "Gudang C-1",
    status: "low-stock",
  },
  {
    id: "8",
    name: "Tissue",
    category: "supplies",
    currentStock: 25,
    minStock: 15,
    maxStock: 50,
    unit: "pack",
    costPerUnit: 12000,
    supplier: "Supplies Central",
    lastRestocked: new Date("2024-01-16"),
    location: "Gudang C-2",
    status: "in-stock",
  },
  {
    id: "9",
    name: "Deterjen",
    category: "supplies",
    currentStock: 3,
    minStock: 5,
    maxStock: 15,
    unit: "botol",
    costPerUnit: 25000,
    supplier: "Cleaning Supplies",
    lastRestocked: new Date("2024-01-08"),
    location: "Gudang C-3",
    status: "low-stock",
  },
  {
    id: "10",
    name: "Mesin Espresso Filter",
    category: "equipment",
    currentStock: 2,
    minStock: 1,
    maxStock: 5,
    unit: "pcs",
    costPerUnit: 45000,
    supplier: "Coffee Equipment",
    lastRestocked: new Date("2024-01-05"),
    location: "Counter",
    status: "in-stock",
  },
]

// ─────────────────────────────
// Suppliers
export const suppliers: Supplier[] = [
  {
    id: "1",
    name: "Kopi Nusantara",
    contact: "081234567890",
    email: "order@kopinusantara.com",
    address: "Jl. Kopi Raya No. 123, Bandung",
    products: ["Biji Kopi Arabika", "Biji Kopi Robusta", "Kopi Bubuk"],
    rating: 4.8,
    paymentTerms: "Net 30",
    deliveryDays: ["Senin", "Rabu", "Jumat"],
  },
  {
    id: "2",
    name: "Dairy Fresh",
    contact: "081234567891",
    email: "supply@dairyfresh.com",
    address: "Jl. Susu Segar No. 456, Bogor",
    products: ["Susu Segar", "Keju", "Yogurt", "Krim"],
    rating: 4.6,
    paymentTerms: "Net 15",
    deliveryDays: ["Selasa", "Kamis", "Sabtu"],
  },
  {
    id: "3",
    name: "Fresh Chicken",
    contact: "081234567892",
    email: "order@freshchicken.com",
    address: "Jl. Ayam Segar No. 789, Depok",
    products: ["Ayam Segar", "Telur", "Daging Sapi"],
    rating: 4.5,
    paymentTerms: "COD",
    deliveryDays: ["Senin", "Rabu", "Jumat", "Sabtu"],
  },
  {
    id: "4",
    name: "Packaging Pro",
    contact: "081234567893",
    email: "sales@packagingpro.com",
    address: "Jl. Kemasan No. 321, Tangerang",
    products: ["Cup Kertas", "Tutup Cup", "Kantong Plastik", "Box Makanan"],
    rating: 4.7,
    paymentTerms: "Net 45",
    deliveryDays: ["Rabu", "Jumat"],
  },
]

// ─────────────────────────────
// Sample Orders
export const sampleOrders: Order[] = [
  {
    id: "1",
    orderNumber: "ORD-001",
    items: [
      { productId: "1", name: "Kopi Susu Gula Aren", price: 18000, quantity: 2 },
      { productId: "9", name: "Nasi Goreng Spesial", price: 25000, quantity: 1 },
    ],
    subtotal: 61000,
    tax: 6100,
    discount: 0,
    total: 67100,
    paymentMethod: "cash",
    status: "preparing",
    customerName: "John Doe",
    orderType: "dine-in",
    tableNumber: 2,
    timestamp: new Date("2024-01-22T10:30:00"),
    notes: "Extra pedas untuk nasi goreng",
    cashierName: "Budi Santoso",
    preparationTime: 15,
  },
  {
    id: "2",
    orderNumber: "ORD-002",
    items: [
      { productId: "2", name: "Es Kopi Susu", price: 15000, quantity: 1 },
      { productId: "31", name: "Pisang Goreng", price: 10000, quantity: 1 },
    ],
    subtotal: 25000,
    tax: 2500,
    discount: 2500,
    total: 25000,
    paymentMethod: "qris",
    status: "ready",
    customerName: "Jane Smith",
    orderType: "takeaway",
    timestamp: new Date("2024-01-22T11:15:00"),
    cashierName: "Budi Santoso",
    preparationTime: 8,
  },
]

// ─────────────────────────────
// Payment Methods
export const paymentMethods = [
  { id: "cash", name: "Tunai", icon: "Banknote", color: "#10B981" },
  { id: "qris", name: "QRIS", icon: "QrCode", color: "#3B82F6" },
  { id: "debit", name: "Kartu Debit", icon: "CreditCard", color: "#8B5CF6" },
  { id: "credit", name: "Kartu Kredit", icon: "CreditCard", color: "#EF4444" },
  { id: "ewallet", name: "E-Wallet", icon: "Smartphone", color: "#F59E0B" },
]

// ─────────────────────────────
// System Settings
export const systemSettings = {
  cafe: {
    name: "Inara Cafe",
    address: "Jl. Kemang Raya No. 123, Jakarta Selatan",
    phone: "021-12345678",
    email: "info@inaracafe.com",
    website: "www.inaracafe.com",
    logo: "/placeholder.svg?height=100&width=100&text=Inara+Cafe",
    taxRate: 10,
    serviceCharge: 0,
    currency: "IDR",
    timezone: "Asia/Jakarta",
  },
  pos: {
    autoLogout: 30,
    printReceipt: true,
    showCustomerDisplay: true,
    allowDiscount: true,
    maxDiscountPercent: 20,
    requireCustomerInfo: false,
    defaultOrderType: "dine-in",
  },
  inventory: {
    lowStockAlert: true,
    autoReorder: false,
    trackExpiry: true,
    expiryAlertDays: 3,
  },
  notifications: {
    newOrder: true,
    lowStock: true,
    staffSchedule: true,
    dailyReport: true,
    email: "manager@inaracafe.com",
    sms: "081234567890",
  },
}
